# Generated by Django 5.1.4 on 2024-12-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_student_options_alter_student_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('1', 'Anganvadi'), ('1', 'LKG'), ('1', 'UKG'), ('2', '1st'), ('2', '2nd'), ('3', '3rd'), ('3', '4th'), ('3', '5th'), ('4', '6th'), ('4', '7th')], max_length=20),
        ),
    ]
