# Generated by Django 5.1.4 on 2024-12-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('Anganvadi', 'Anganvadi'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th')], default=1, help_text='Class name in words (e.g., 1st, 2nd, etc.)', max_length=20),
            preserve_default=False,
        ),
    ]
